version: "3.9"

services:
  redis:
    image: redis
    restart: always

  web:
    build:
      context: .
    restart: always
    ports:
      - "8000:8000"
    command: ['python3', 'manage.py', 'runserver', '0.0.0.0:8000']

  worker:
    build:
      context: .
    restart: always
    command: ['celery', '-A', 'FileProcessing.celery:app', 'worker', '--loglevel=INFO']
    depends_on:
      - redis


  flower:
    build:
      context: .
    restart: always
    command: [ 'celery', '-A', 'FileProcessing.celery:app', 'flower']
    depends_on:
      - redis
